[package]
name = "tcpklien"
version = "0.1.0"
edition = "2021"

[dependencies]
aerolib = { path = "../src-tauri/aerolib", features = ["aeronet"] }
anyhow = "1.0.93"
tokio = { version = "1.41.1", features = ["full"] }
