name: Build & Deploy BADAQ

on:
  push:
    branches:
      - main
      - master

jobs:
  update_release_draft:
    name: Draft The Release
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
